//This file contains all the links 
var links = [
    "https://ubuntu.com/",
    "http://ubuntuce.com/",
    "https://pop.system76.com/",
    "https://www.kali.org/",
    "https://tails.boum.org/",
    "https://www.debian.org/",
    "https://archlinux.org/",
    "https://www.gentoo.org/",
    "https://linuxmint.com/",
    "https://getfedora.org/",
    "https://developers.redhat.com/products/rhel/download",
    "https://os.gnome.org/",
    "https://manjaro.org/",
    "https://chromeenterprise.google/os/",
    "https://xubuntu.org/",
    "https://kubuntu.org/",
    "https://www.raspberrypi.org/software/",
    "https://store.steampowered.com/steamos",
    "https://www.centos.org/",
    "https://www.opensuse.org/",
    "https://www.openmandriva.org/",
    "https://www.clearos.com/",
    "https://www.oracle.com/linux/",
    "https://scientificlinux.org/",
    "https://www.qubes-os.org/",
    "https://geckolinux.github.io/",
    "https://www.mageia.org/en/",
    "https://www.rosalinux.ru/en/home-2/",
    "https://www.pclinuxos.com/",
    "https://en.altlinux.org/Downloads",
    "https://www.pureos.net/",
    "https://astralinux.ru/en/",
    "https://www.parrotsec.org/",
    "https://lubuntu.net/",
    "https://ubuntubudgie.org/",
    "https://ubuntu-mate.org/",
    "https://ubuntustudio.org/",
    "https://www.edubuntu.org/",
    "https://www.backbox.org/",
    "https://zorinos.com/",
    "https://galliumos.org/",
    "https://elementary.io/",
    "https://ubuntuunity.org/",
    "https://emmabuntus.org/category/english/",
    "https://neon.kde.org/",
    "https://www.linuxliteos.com/",
    "http://www.linuxmce.org/",
    "https://www.bodhilinux.com/",
    "https://www.blue-systems.com/products/software/netrunner/",
    "https://www.gooroom.kr/",
    "https://trisquel.info/",
    "https://peppermintos.com/",
    "https://www.slax.org/",
    "https://solydxk.com/",
    "https://antixlinux.com/",
    "https://mxlinux.org/",
    "https://bosslinux.in/",
    "https://www.primeos.in/download/",
    "http://www.knopper.net/knoppix/index-en.html",
    "https://www.devuan.org/",
    "https://www.deepin.org/en/",
    "https://www.crunchbangplusplus.org/",
    "http://www.damnsmalllinux.org/",
    "https://archbang.org/",
    "https://artixlinux.org/",
    "https://archlabslinux.com/",
    "https://www.blackarch.org/",
    "https://www.chakralinux.org/",
    "https://endeavouros.com/",
    "https://www.frugalware.org/",
    "https://www.hyperbola.info/",
    "https://www.calculate-linux.org/",
    "https://www.chromium.org/chromium-os",
    "https://pentoo.ch/",
    "https://www.sabayon.org/",
    "https://nimblex.net/",
    "https://salixos.org/",
    "https://www.supergamer.x10host.com/",
    "http://topologi-linux.sourceforge.net/",
    "http://www.porteus.org/",
    "https://www.dnalinux.com/",
    "http://www.zenwalk.org/",
    "http://www.lunar-linux.org/",
    "https://guix.gnu.org/",
    "https://www.foresightlinux.org/",
    "https://www.gobolinux.org/",
    "https://www.hpcfactor.com/reviews/software/jlime/donkey-1-0-2/",
    "https://voidlinux.org/",
    "http://www.toms.net/rb/",
    "http://www.tinycorelinux.net/",
    "https://getsol.us/home/",
    "https://slitaz.org/en/",
    "https://puppylinux.com/",
    "https://openwrt.org/",
    "https://nixos.org/",
    "https://www.mklinux.org/",
    "http://www.dragora.org/en/index.html",
    "https://crux.nu/",
    "https://www.alpinelinux.org/",
    "https://armbian.com",
    "https://qntm.org/suicide",
    "http://www.slackware.com/",
    "https://www.parabola.nu/",
    "https://bedrocklinux.org/",
    "https://instantos.io",
    "https://maboxlinux.org/",
    "https://ferenos.weebly.com/",
    "https://rebornos.org/",
    "https://endlessos.com/home/",
    "https://www.elivecd.org/",
    "https://q4os.org/index.html",
    "https://reactos.org/",
    "https://garudalinux.org/",
    "https://www.system-rescue.org/Download/",
    "https://kaosx.us/",
    "https://voyagerlive.org/", //who ever made this website really needs improve their image quality and streatch resolution :/ 
    "https://www.bunsenlabs.org/",
    "https://lxle.net/",
    "https://tos.odex.be/",
     "https://thinstation.github.io/thinstation/",
    "https://spi.dod.mil/lipose.htm", //not only is this distro having issues with security for it's website, the funding ended. Might move to EOL so I would have to keep an eye on them
    "https://sourceforge.net/projects/rebeccablackos/", //Rebecca Black operating system 
    "https://caixamagica.pt/en/linux-cm",
    "https://easynas.org/",
    "https://arcolinux.com/",
    "https://arcolinuxb.com/", //this linux has two different websites
    "https://regolith-linux.org/",
    "https://silverblue.fedoraproject.org/",
    "https://amogos.studio/", //ඞ sus
    "https://almalinux.org",
    "https://ibuntuos.com",
    "https://nxos.org/",
    "https://ultramarine-linux.org",
    "https://en.cutefishos.com/", //the website takes ages to load, if ever
    "https://www.ghostbsd.org/",
    "https://www.freebsd.org/",
    "https://www.openbsd.org/",
    "https://www.netbsd.org/",
    "https://www.dragonflybsd.org/",
    "https://www.midnightbsd.org/",
    "https://nomadbsd.org/",
    "https://hellosystem.github.io/"
];

var EOLlinks = [
    "https://archiveos.org/redstar/", 
    //RedStarOS's website's inactive directory is called www.naenara.com.kp/en/kcc/ and naenara in korea means my country (내나라) pretty creative I guess
    "http://hannahmontana.sourceforge.net/", //yes.
    "https://archiveos.org/linux-xp/",
    "https://archiveos.org/yellowdog/",
    "https://archiveos.org/kateos/",
    "https://archiveos.org/caldera/",
    "https://archiveos.org/lps/",
    "https://archiveos.org/vector/",
    "https://archiveos.org/feather/",
    "https://archiveos.org/dreamlinux/",
    "https://www.kanotix.org/",
    "https://archiveos.org/handy/",
    "https://archiveos.org/kurumin/",
    "https://archiveos.org/sabily/",
    "https://www.nova.cu/",
    "https://archiveos.org/cub/",
    "https://archiveos.org/max/",
    "https://sites.google.com/site/poseidonlinux/Home",
    "https://archiveos.org/nepalinux/",
    "http://berry.osdn.jp/",
    'https://vinelinux.org/',
    "https://sparkylinux.org/",
    "https://peachosi.com/", //a little worried about this one hope I don't get in trouble 
    "https://emmett31.wixsite.com/lightninglinux",
    "https://archiveos.org/advanced/",
    "https://archiveos.org/mydebian/",
    "https://archiveos.org/netlinx/",
    "https://archiveos.org/ubuntubsd/",
    "https://archiveos.org/64studio/",
    "https://archiveos.org/accelerated-knoppix/",
    "https://archiveos.org/alinux/",
    "https://archbox-linux.github.io/",
    "https://archiveos.org/arch-anywhere/",
    "https://archiveos.org/archeos/",
    "https://archiveos.org/architect/",
    "https://www.backtrack-linux.org/",
    "https://archiveos.org/archmerge/",
    "https://archiveos.org/bellaos/",
    "https://archiveos.org/blackaudit/",
    "http://biebian.sourceforge.net/", //this is the best linux distro ever lmao
    "https://archiveos.org/bubuntu/",
    "https://blankon.id/",
    "http://environmentalomics.org/bio-linux/",
    "https://archiveos.org/black-lab/",
    "https://archiveos.org/saluki/",
    "https://www.caelinux.com/CMS3/",
    "https://archiveos.org/carolina/",
    "https://archiveos.org/ubuntu-satanic/", //in the other spectrum we have satanic ubuntu
    "https://www.caine-live.net/",
    "https://archiveos.org/asplinux/",
    "https://archiveos.org/tao/",
    "https://archiveos.org/topologilinux/",
    "https://archiveos.org/startcom/",
    "https://archiveos.org/rivendell/",
    "https://archiveos.org/united/",
    "https://archiveos.org/caixa-magica/",
    "https://archiveos.org/karamad/",
    "http://urix.us/",
    "https://archiveos.org/delix/",
    "https://archiveos.org/vlos/",
    "https://archiveos.org/slontoo/",
    "https://gentoox.shallax.com/",
    "https://archiveos.org/gentooth/",
    "https://archiveos.org/cloveros/",
    "https://archiveos.org/bintoo/",
    "https://archiveos.org/phaeronix/",
    "https://archiveos.org/bitdefender/",
    "https://archiveos.org/muriqui/",
    "https://archiveos.org/kde-four-live/",
    "https://www.stresslinux.org/sl/",
    "https://archiveos.org/astaro/",
    "https://archiveos.org/antergos/",
    "https://www.jolicloud.com/jolios/",
    "https://www.backslashlinux.com/",
    "http://www.ututo.org/en/"
];


var debianlinks = [
    "https://ubuntu.com/",
    "https://pop.system76.com/",
    "https://www.kali.org/",
    "https://tails.boum.org/",
    "https://www.debian.org/",
    "https://linuxmint.com/",
    "https://xubuntu.org/",
    "https://kubuntu.org/",
    "https://www.raspberrypi.org/software/",
    "https://store.steampowered.com/steamos",
    "https://www.pureos.net/",
    "https://astralinux.ru/en/",
    "https://www.parrotsec.org/",
    "https://lubuntu.net/",
    "https://ubuntubudgie.org/",
    "https://ubuntu-mate.org/",
    "https://ubuntustudio.org/",
    "https://www.edubuntu.org/",
    "https://www.backbox.org/",
    "https://zorinos.com/",
    "https://galliumos.org/",
    "https://elementary.io/",
    "https://ubuntuunity.org/",
    "https://neon.kde.org/",
    "https://www.linuxliteos.com/",
    "http://www.linuxmce.org/",
    "https://www.bodhilinux.com/",
    "https://www.blue-systems.com/products/software/netrunner/",
    "https://www.gooroom.kr/",
    "https://trisquel.info/",
    "https://peppermintos.com/",
    "https://www.slax.org/",
    "https://solydxk.com/",
    "https://antixlinux.com/",
    "https://mxlinux.org/",
    "https://bosslinux.in/",
    "https://www.primeos.in/download/",
    "http://www.knopper.net/knoppix/index-en.html",
    "https://www.devuan.org/",
    "https://www.deepin.org/en/",
    "https://www.crunchbangplusplus.org/",
    "http://www.damnsmalllinux.org/",
    "https://getsol.us/home/",
    "https://armbian.com",
    "https://qntm.org/suicide",
    "https://ferenos.weebly.com/",
    "https://endlessos.com/home/",
    "https://www.elivecd.org/",
    "https://q4os.org/index.html",
    "https://voyagerlive.org/",
    "https://www.bunsenlabs.org/",
    "https://lxle.net/",
    "https://sourceforge.net/projects/rebeccablackos/", //Rebecca Black operating system 
    "https://regolith-linux.org/",
    "https://www.jostroos.ml/amogos/", //impasta 
    "https://ibuntuos.com",
    "https://nxos.org/",
    "https://en.cutefishos.com/",
    "http://ubuntuce.com/"
];

var EOLdebianlinks = [
    "http://hannahmontana.sourceforge.net/", //very much yes.
    "https://archiveos.org/feather/",
    "https://archiveos.org/dreamlinux/",
    "https://www.kanotix.org/",
    "https://archiveos.org/handy/",
    "https://archiveos.org/kurumin/",
    "https://archiveos.org/sabily/",
    "https://www.nova.cu/",
    "https://archiveos.org/cub/",
    "https://archiveos.org/max/",
    "https://sites.google.com/site/poseidonlinux/Home",
    "https://archiveos.org/nepalinux/",
    "https://sparkylinux.org/",
    "https://peachosi.com/",
    "https://archiveos.org/advanced/",
    "https://archiveos.org/mydebian/",
    "https://archiveos.org/ubuntubsd/",
    "https://archiveos.org/64studio/",
    "https://archiveos.org/accelerated-knoppix/",
    "https://www.backtrack-linux.org/",
    "https://archiveos.org/bellaos/",
    "https://archiveos.org/blackaudit/",
    "https://archiveos.org/bubuntu/",
    "http://environmentalomics.org/bio-linux/",
    "https://archiveos.org/black-lab/",
    "https://www.caelinux.com/CMS3/",
    "https://archiveos.org/ubuntu-satanic/", //not sure if this distro has book of sin included
    "https://www.caine-live.net/",
    "https://archiveos.org/caixa-magica/",
    "https://archiveos.org/delix/",
    "https://archiveos.org/muriqui/",
    "https://www.jolicloud.com/jolios/",
    "https://www.backslashlinux.com/"
];

var archlinks = [
    "https://archlinux.org/",
    "https://manjaro.org/",
    "https://archbang.org/",
    "https://artixlinux.org/",
    "https://archlabslinux.com/",
    "https://www.blackarch.org/",
    "https://www.chakralinux.org/",
    "https://endeavouros.com/",
    "https://www.frugalware.org/",
    "https://www.hyperbola.info/",
    "https://www.parabola.nu/",
    "https://instantos.io",
    "https://maboxlinux.org/",
    "https://garudalinux.org/",
    "https://tos.odex.be/",
    "https://arcolinux.com/",
    "https://arcolinuxb.com/",
    "https://rebornos.org/"
];

var EOLarchlinks = [
    "https://archbox-linux.github.io/",
    "https://archiveos.org/archeos/",
    "https://archiveos.org/architect/",
    "https://archiveos.org/archmerge/",
    "https://archiveos.org/antergos/",
    "http://justbrowsinglinux.com/" //Cool but last release was in 2014
];

var gentoolinks = [
    "https://www.gentoo.org/",
    "https://chromeenterprise.google/os/",
    "https://www.calculate-linux.org/",
    "https://www.chromium.org/chromium-os",
    "https://pentoo.ch/",
    "https://www.system-rescue.org/Download/"
];

var EOLgentoolinks = [
    "https://archiveos.org/vlos/",
    "https://archiveos.org/slontoo/",
    "https://gentoox.shallax.com/",
    "https://archiveos.org/gentooth/",
    "https://archiveos.org/cloveros/",
    "https://archiveos.org/bintoo/",
    "https://archiveos.org/phaeronix/",
    "https://archiveos.org/bitdefender/"
]; 

var slacklinks = [
    "http://www.slackware.com/",
    "https://nimblex.net/",
    "https://salixos.org/",
    "https://www.supergamer.x10host.com/",
    "http://topologi-linux.sourceforge.net/",
    "http://www.porteus.org/",
    "https://www.dnalinux.com/",
    "http://www.zenwalk.org/"
];

var EOLslacklinks = [
    "https://archiveos.org/vector/",
    "https://archiveos.org/topologilinux/",
    "https://archiveos.org/rivendell/"
];

var redhatlinks = [
    "https://getfedora.org/",
    "https://developers.redhat.com/products/rhel/download",
    "https://www.centos.org/",
    "https://www.openmandriva.org/",
    "https://www.clearos.com/",
    "https://www.oracle.com/linux/",
    "https://scientificlinux.org/",
    "https://www.mageia.org/en/",
    "https://www.rosalinux.ru/en/home-2/",
    "https://www.pclinuxos.com/",
    "https://en.altlinux.org/Downloads",
    "https://silverblue.fedoraproject.org/",
    "https://almalinux.org",
    "https://ultramarine-linux.org"
];

var EOLredhatlinks = [
    "https://archiveos.org/redstar/", 
    "https://archiveos.org/linux-xp/",
    "https://archiveos.org/yellowdog/",
    "http://berry.osdn.jp/",
    'https://vinelinux.org/',
    "https://archiveos.org/asplinux/",
    "https://archiveos.org/tao/",
    "https://archiveos.org/startcom/"
];

var suselinks = [ //there aren't a lot of suse unfortunetly 
    "https://www.opensuse.org/",
    "https://geckolinux.github.io/",
    "https://easynas.org/"
];

var EOLsuselinks = [
    "https://archiveos.org/united/",
    'https://archiveos.org/karamad/',
    "http://urix.us/",
    "https://archiveos.org/kde-four-live/",
    "https://www.stresslinux.org/sl/",
    "https://archiveos.org/astaro/"
]; 

var otherlinks =[
    "http://www.lunar-linux.org/",
    "https://guix.gnu.org/",
    "https://www.foresightlinux.org/",
    "https://www.gobolinux.org/",
    "https://www.hpcfactor.com/reviews/software/jlime/donkey-1-0-2/",
    "https://voidlinux.org/",
    "http://www.toms.net/rb/",
    "http://www.tinycorelinux.net/",
    "https://slitaz.org/en/",
    "https://puppylinux.com/",
    "https://openwrt.org/",
    "https://nixos.org/",
    "https://www.mklinux.org/",
    "http://www.dragora.org/en/index.html",
    "https://crux.nu/",
    "https://www.alpinelinux.org/",
    "https://bedrocklinux.org/",
    "https://kaosx.us/",
    "https://thinstation.github.io/thinstation/",
    "https://www.ghostbsd.org/",
    "https://www.freebsd.org/",
    "https://www.openbsd.org/",
    "https://www.netbsd.org/",
    "https://www.dragonflybsd.org/",
    "https://www.midnightbsd.org/",
    "https://nomadbsd.org/",
    "https://hellosystem.github.io/",
    "https://www.freedos.org/",
    "https://www.dosbox.com/",
    "https://asahilinux.org/",
    "https://cb-linux.github.io/breath/"
];
var EOLotherlinks = [
    "https://archiveos.org/kateos/",
    "https://archiveos.org/caldera/",
    "https://archiveos.org/lps/",
    "https://emmett31.wixsite.com/lightninglinux",//parent unknown. come back to it later
    "https://archiveos.org/netlinx/",
    "https://archiveos.org/alinux/",
    "http://biebian.sourceforge.net/", 
    //yeah it turns out biebian is not part of Debian or Ubuntu (shoking) it's acutally part of Puppy Linux which was part of a joke
    "https://blankon.id/", //parent distribution uknown, check out later
    "https://archiveos.org/saluki/",
    "https://archiveos.org/carolina/",
    "https://web.archive.org/web/20210720175650/https://spi.dod.mil/lipose.htm" 
];
